### ISSUE TITLE
HELP ME WITH COINFY

### ISSUE THREAD

**Issue by DOSFOKDSFOK** [Josema/biwenger-hacks#1]
HELP ME WITH COINFY

**Comment by Josema** [comment]
What's wrong?

**Comment by DOSFOKDSFOK** [comment]
> What's wrong?

i created wallet i have 12 words and password i cant login to wallet please help me

**Comment by DOSFOKDSFOK** [comment]
Sorry for spamming

**Comment by Josema** [comment]
I need more info. If you have your password and your 12 words why you can't login?

Have a look this issue. It might help:
https://github.com/elevenyellow/coinfy/issues/38

**Comment by DOSFOKDSFOK** [comment]
I even created a new wallet to check your site, it's impossible to connect the wallet, I read the article you sent me, it didn't work

**Comment by Josema** [comment]
Try importing your 12 words in Exodus wallet.
https://www.exodus.com/support/article/925-everything-you-need-to-know-about-the-secret-recovery-phrase#using

**Comment by DOSFOKDSFOK** [comment]
I did as it is written there, entered 12 words of the wallet that I created on coinfy created a password, but still it does not give out my wallet and balance 0

**Comment by DOSFOKDSFOK** [comment]
Please help me

**Comment by Josema** [comment]
Do you have funds on BTC, ETH or any other?

**Comment by DOSFOKDSFOK** [comment]
yes on btc

**Comment by DOSFOKDSFOK** [comment]
please can we contact you by mail?

**Comment by Josema** [comment]
Try this:
1. Go to https://iancoleman.io/bip39/
2. Introduce your 12 words in the **BIP39 Mnemonic** box
3. Select **Derivation Path: BIP49**
4. In the **Derived Addresses** area check if any of your generated addresses has funds on https://www.blockchain.com/explorer/blocks/btc
5. If so, copy the **Private key** associated to that address
6. Import that private key on **Exodus wallet**. Example: https://github.com/elevenyellow/coinfy/issues/38#issuecomment-1050220566

**Comment by DOSFOKDSFOK** [comment]
Thank you very much I love you
